name: Pull requests validation

# This workflow file is triggered on every pull request
on:
  pull_request:
    branches:
      - "*"

jobs:
  # Test and build the project
  test-and-build:
    # Define operating system
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint project
        run: npm run lint

      - name: Build project
        run: npm run build
